### ISSUE TITLE
老哥

### ISSUE THREAD

**Issue by aaq1adqwe** [depycode/fastjson-local-echo#1]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.fastjson.JSONException: autoType is not support. org.apache.tomcat.dbcp.dbcp2.BasicDataSource] with root cause

本地复现会报这个错，能问下知道解决办法嘛

**Comment by depycode** [comment]
fastjson 什么版本啊

**Comment by aaq1adqwe** [comment]
就是你pom.xml里面的，1.2.47

**Comment by depycode** [comment]
jdk 啥版本啊，试试  java version "1.8.0_192"
